name: app
type: python:3.5

dependencies:
    python:
       uwsgi: "*"

web:
    commands:
       start: "uwsgi --ini conf/uwsgi.ini"

    locations:
        "/":
            root: "public"
            passthru: true
            expires: 1h

disk: 512